document.write('<link rel=\"stylesheet\" href=\"http://www.ncc-cma.net/css/cmdp.css?v=1668584398\">');
document.write('<div class=\"header\">');
document.write('<div class=\"header-tit clearfix\">');
document.write('<div class=\"w1200\">');
document.write('<span>2023年&nbsp;&nbsp;05月27日&nbsp;&nbsp;星期六</span>');
document.write('<div class=\"fr\" style=\"position: relative;\">');
document.write('');
document.write('<span><a href=\"http://bcc.ncc-cma.net/\" target=\"_blank\">English</a> / <span class=\"header-weixin\">微信</span><div class=\"header-weixin-img\">');
document.write('<img src=\"http://www.ncc-cma.net/images/erweima.png\" alt=\"\">');
document.write('</div> / <a href=\"http://cmdp.ncc-cma.net/users/\" target=\"_blank\">会员中心(User)</a></span>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class=\"w1200\">');
document.write('<img class=\"logo\" src=\"https://www.cuit.edu.cn/images/logo_03.png" alt=\"\">');
document.write('<div class=\"header-bcc\">');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class=\"head_nav clearfix\">');
document.write('<div class=\"container\">');
document.write('<ul>');
document.write('<li><a href=\"http://www.ncc-cma.net/\"><span>首页</span></a></li>');
document.write('<li>');
document.write('<a href=\"http://www.ncc-cma.net/channel/aboutus\"');
document.write('target=\"_self\"><span>中心概况</span></a>');
document.write('<ul class=\"second_nav\">');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/index/wid/12\"');
document.write('target=\"_self\">中心简介</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/index/wid/13\"');
document.write('target=\"_self\">机构设置</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/index/wid/15\"');
document.write('target=\"_self\">中心领导</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/index/wid/14\"');
document.write('target=\"_self\">历史沿革</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/index/wid/20\"');
document.write('target=\"_self\">联系我们</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li>');
document.write('<a href=\"http://www.ncc-cma.net/channel/index/wid/158\"');
document.write('target=\"_self\"><span>工作动态</span></a>');
document.write('</li>');
document.write('<li class=\"active\">');
document.write('<a href=\"http://cmdp.ncc-cma.net/\"');
document.write('target=\"_self\"><span>业务服务</span></a>');
document.write('<ul class=\"second_nav\">');
document.write('<li><a href=\"http://cmdp.ncc-cma.net/cn/monitoring.htm\"');
document.write('target=\"_self\">气候监测</a></li>');
document.write('<li><a href=\"http://cmdp.ncc-cma.net/cn/prediction.htm\"');
document.write('target=\"_self\">气候预测</a></li>');
document.write('<li><a href=\"http://cmdp.ncc-cma.net/cn/application.htm\"');
document.write('target=\"_self\">气候灾害与影响评价</a></li>');
document.write('<li><a href=\"http://cmdp.ncc-cma.net/cn/download.htm\"');
document.write('target=\"_self\">气候服务</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li>');
document.write('<a href=\"http://www.ncc-cma.net/channel/detail/169\"');
document.write('target=\"_self\"><span>科技创新</span></a>');
document.write('<ul class=\"second_nav\">');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/detail/169\"');
document.write('target=\"_self\">科研项目</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/detail/200\"');
document.write('target=\"_self\">科研成果</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/detail/171\"');
document.write('target=\"_self\">创新平台</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/index/wid/180\"');
document.write('target=\"_self\">创新团队</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/experts/lists\"');
document.write('target=\"_self\">专家团队</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/index/wid/181\"');
document.write('target=\"_self\">学术活动</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li>');
document.write('<a href=\"http://www.ncc-cma.net/channel/index/wid/173\"');
document.write('target=\"_self\"><span>气候科普</span></a>');
document.write('</li>');
document.write('<li>');
document.write('<a href=\"http://www.ncc-cma.net/channel/index/wid/101\"');
document.write('target=\"\"><span>公告通知</span></a>');
document.write('</li>');
document.write('<li>');
document.write('<a href=\"http://www.ncc-cma.net/channel/product/index\"');
document.write('target=\"_self\"><span>技术合作</span></a>');
document.write('<ul class=\"second_nav\">');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/product/service\"');
document.write('target=\"_self\">合作方向</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/product\"');
document.write('target=\"_self\">气候产品清单</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/product/extension\"');
document.write('target=\"_self\">系统开发</a></li>');
document.write('<li><a href=\"http://www.ncc-cma.net/channel/product/application\"');
document.write('target=\"_self\">应用案例</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('</ul>');
document.write('</div>');
document.write('</div>');